/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: b42bce3beff39500936304e5572fef22)
interface __BaseEnv_Env {
	CF_ACCOUNT_ID: "bd47c21b1d04bbd68d667e2f1760d95f";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCOUNT_ID">> {}
}
